/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthedRouteImport } from "./routes/_authed";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthedIndexRouteImport } from "./routes/_authed/index";
import { Route as AuthedOperationsRouteImport } from "./routes/_authed/operations";
import { Route as AuthedPlansRouteImport } from "./routes/_authed/plans";
import { Route as AuthedProjectsRouteImport } from "./routes/_authed/projects";
import { Route as AuthedRunsIndexRouteImport } from "./routes/_authed/runs/index";
import { Route as AuthedRunsRunKeyRouteImport } from "./routes/_authed/runs/$runKey";

const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedOperationsRoute = AuthedOperationsRouteImport.update({
  id: "/operations",
  path: "/operations",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedPlansRoute = AuthedPlansRouteImport.update({
  id: "/plans",
  path: "/plans",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedProjectsRoute = AuthedProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedRunsIndexRoute = AuthedRunsIndexRouteImport.update({
  id: "/runs/",
  path: "/runs/",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedRunsRunKeyRoute = AuthedRunsRunKeyRouteImport.update({
  id: "/runs/$runKey",
  path: "/runs/$runKey",
  getParentRoute: () => AuthedRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthedIndexRoute;
  "/login": typeof LoginRoute;
  "/operations": typeof AuthedOperationsRoute;
  "/plans": typeof AuthedPlansRoute;
  "/projects": typeof AuthedProjectsRoute;
  "/runs/$runKey": typeof AuthedRunsRunKeyRoute;
  "/runs/": typeof AuthedRunsIndexRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/operations": typeof AuthedOperationsRoute;
  "/plans": typeof AuthedPlansRoute;
  "/projects": typeof AuthedProjectsRoute;
  "/": typeof AuthedIndexRoute;
  "/runs/$runKey": typeof AuthedRunsRunKeyRoute;
  "/runs": typeof AuthedRunsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_authed": typeof AuthedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_authed/operations": typeof AuthedOperationsRoute;
  "/_authed/plans": typeof AuthedPlansRoute;
  "/_authed/projects": typeof AuthedProjectsRoute;
  "/_authed/": typeof AuthedIndexRoute;
  "/_authed/runs/$runKey": typeof AuthedRunsRunKeyRoute;
  "/_authed/runs/": typeof AuthedRunsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/operations"
    | "/plans"
    | "/projects"
    | "/runs/$runKey"
    | "/runs/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/login"
    | "/operations"
    | "/plans"
    | "/projects"
    | "/"
    | "/runs/$runKey"
    | "/runs";
  id:
    | "__root__"
    | "/_authed"
    | "/login"
    | "/_authed/operations"
    | "/_authed/plans"
    | "/_authed/projects"
    | "/_authed/"
    | "/_authed/runs/$runKey"
    | "/_authed/runs/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/": {
      id: "/_authed/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthedIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/operations": {
      id: "/_authed/operations";
      path: "/operations";
      fullPath: "/operations";
      preLoaderRoute: typeof AuthedOperationsRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/plans": {
      id: "/_authed/plans";
      path: "/plans";
      fullPath: "/plans";
      preLoaderRoute: typeof AuthedPlansRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/projects": {
      id: "/_authed/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof AuthedProjectsRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/runs/": {
      id: "/_authed/runs/";
      path: "/runs";
      fullPath: "/runs/";
      preLoaderRoute: typeof AuthedRunsIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/runs/$runKey": {
      id: "/_authed/runs/$runKey";
      path: "/runs/$runKey";
      fullPath: "/runs/$runKey";
      preLoaderRoute: typeof AuthedRunsRunKeyRouteImport;
      parentRoute: typeof AuthedRoute;
    };
  }
}

interface AuthedRouteChildren {
  AuthedOperationsRoute: typeof AuthedOperationsRoute;
  AuthedPlansRoute: typeof AuthedPlansRoute;
  AuthedProjectsRoute: typeof AuthedProjectsRoute;
  AuthedIndexRoute: typeof AuthedIndexRoute;
  AuthedRunsRunKeyRoute: typeof AuthedRunsRunKeyRoute;
  AuthedRunsIndexRoute: typeof AuthedRunsIndexRoute;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOperationsRoute: AuthedOperationsRoute,
  AuthedPlansRoute: AuthedPlansRoute,
  AuthedProjectsRoute: AuthedProjectsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedRunsRunKeyRoute: AuthedRunsRunKeyRoute,
  AuthedRunsIndexRoute: AuthedRunsIndexRoute,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
